title: Risto Vuorio
email_full: mailto:riv@umich.edu
linkedin: ristovuorio
github: vuoristo

description: >-
  Risto Vuorio is a visiting scholar at University of Michigan.
baseurl: ""
url: "https://vuoristo.github.io"

# Build settings
markdown: kramdown