title: Risto Vuorio
email: riv@umich.edu
description: >-
  Risto Vuorio is a visiting scholar at University of Michigan.
baseurl: ""
url: "https://vuoristo.github.io"
github_username:  vuoristo

# Build settings
markdown: kramdown